# Site settings
title: For My Demi
header-img: img/home-bg.jpg
email: sturridge_qin@163.com
description: "test"
baseurl: ""
url: "http://mydemi.github.io"
twitter_username: null
github_username:  mydemi
facebook_username:  null
weibo_username: null
zhihu_username: null

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
